name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      plan_run_id:
        description: "Run ID del workflow Terraform Plan"
        required: true

env:
  TF_VERSION: "1.5.0"
  TF_WORKING_DIR: "."

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: terraform-apply

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - run: terraform init -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}

      - uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          run-id: ${{ inputs.plan_run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: terraform show -no-color tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}

      - run: terraform apply -input=false tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}
